learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('learning_logs.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

learning_logs/urls.py
from django.urls import path
from . import views

app_name = 'learning_logs'
urlpatterns = [
    # Домашняя страница
    path('', views.index, name='index'),
    # Страница со списком всех тем
    path('topics/', views.topics, name='topics'),
    path('topics/<int:topic_id>', views.topic, name='topic'),
    # Страница для добавления новой темы
    path('new_topic/', views.new_topic, name='new_topic'),
    # Страница для добавления новой записи
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    # Страница для редактирования страницы
    path('edit_entry/<int:entry_id>', views.edit_entry, name='edit_entry'),
    # Удаление записи
    path('delete_entry/<int:entry_id>/', views.delete_entry, name='delete_entry'),
    # Удаление темы
    path('delete_topic/<int:topic_id>/', views.delete_topic, name='delete_topic'),
    # Редактирование темы
    path('edit_topic/<int:topic_id>/', views.edit_topic, name='edit_topic')


]

users/urls.py
"""Определяет схемы URL для пользователей"""

from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
    # Включить URL авторизации по умолчанию.
    path('', include('django.contrib.auth.urls')),
    # Страница регистрации.
    path('register/', views.register, name='register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User



class Topic(models.Model):
    """Тема которую изучает пользователь"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Возвращает строковое представление модели"""
        return self.text

class Entry(models.Model):
    """Информация изученная пользователем по теме"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    # date_added = models.DateTimeField(default=timezone.now)


    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Возвращает строковое предствавление модели"""
        if len(self.text) > 50:
            return f"{self.text[:50]}..."
        else:
            return self.text

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms
from .models import Topic, Entry

class TopicForm(forms .ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms .ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404
# import pytz
# from django.utils import timezone

from .models import Topic, Entry
from .forms import TopicForm, EntryForm



def index(request):
    return render(request, 'learning_logs/index.html')

@login_required()
def topics(request):
    """Выводит список всех тем"""
    # timezone.activate(pytz.timezone("Europe/Moscow"))
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

def check_topic_owner(topic, request):
    """Проверяет, что пользователь, связанный с темой, является текущим пользователем"""
    if topic.owner != request.user:
        raise Http404

@login_required()
def topic(request, topic_id):
    """Выводит одну тему и все ее записи"""
    topic = Topic.objects.get(id=topic_id)
    # Проверка того, что тема принадлежит текущему пользователю
    check_topic_owner(topic, request)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

@login_required()
def new_topic(request):
    """Определяет новую тему"""
    if request.method != 'POST':
        # Данные не отправились; создается пустая форма
        form = TopicForm()
    else:
        # Отправлены данные POST; обратботать данные
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('learning_logs:topics')
    # Вывести пустую или недействительную форму
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required()
def new_entry(request, topic_id):
    """Добавляет новую запись по конкретной теме"""
    topic = Topic.objects.get(id=topic_id)
    check_topic_owner(topic, request)

    if request.method != 'POST':
        # Данные не отправились; создается пустая форма
        form = EntryForm()
    else:
        # Отправлены данные POST; обратботать данные
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id=topic_id)

    # Вывести недействительную или пустую форму
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)

@login_required()
def edit_entry(request,entry_id):
    """Редактирует существующую запись"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    check_topic_owner(topic, request)

    if request.method != 'POST':
        # Исходный запрос; форма заполняется данными текущей записи
        form = EntryForm(instance=entry)
    else:
        # Отправка данных POST; обработать данные
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

@login_required()
def delete_entry(request, entry_id):
    try:
        entry = Entry.objects.get(id=entry_id)
    except Entry.DoesNotExist:
        raise Http404("Запись не найдена")
    entry.delete()
    return redirect('learning_logs:topic', topic_id=entry.topic.id)

@login_required()
def delete_topic(request, topic_id):
    """Удаляет тему"""
    topic = Topic.objects.get(id=topic_id)
    # Проверка того, что тема принадлежит текущему пользователю
    check_topic_owner(topic, request)

    if request.method == 'POST':
        # Подтверждение удаления темы
        topic.delete()
        return redirect('learning_logs:topics')

    # Вывести страницу подтверждения удаления темы
    context = {'topic': topic}
    return render(request, 'learning_logs/delete_topic.html', context)

def edit_topic(request, topic_id):
    """Редактирует существующую тему."""
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        # Исходный запрос; форма заполняется данными текущей записи.
        form = TopicForm(instance=topic)
    else:
        # Отправка данных POST; обработать данные.
        form = TopicForm(instance=topic, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)

    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_topic.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
    """Регистрирует нового пользователя"""
    if request.method != 'POST':
        """Выводит пустую форму регистрации"""
        form = UserCreationForm()
    else:
        """Обработка заполненной формы"""
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            """Выполнение входа и перенаправление на домашнюю страницу"""
            login(request, new_user)
            return redirect('learning_logs:index')

    # Вывести пустую или недействительную форму
    context = {'form': form}
    return render(request, 'registration/register.html', context)

learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %}
{% load static %}

<!doctype html>

<html lang="ru">
  <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1,
            shrink-to-fit=no">
      <title>Leaning Log</title>

      {% bootstrap_css %}
      {% bootstrap_javascript jquery='full' %}

      <link rel="stylesheet" href="{% static 'learning_logs/css/styles.css' %}">
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">

  </head>
  <body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4 border">
        <a class="navbar-brand" href="{% url 'learning_logs:index' %}">Learning Log</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarCollapse" aria-controls="navbarCollapse"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span></button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'learning_logs:topics' %}">
                      <i class="fas fa-folder-open"></i> Темы</a></li>
            </ul>
            <ul class="navbar-nav ml-auto">
              {% if user.is_authenticated %}
                <li class="nav-item">
                    <span class="navbar-text">Здравствуйте, {{ user.username }}.</span>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'users:logout' %}">
                      <i class="fas fa-sign-out-alt"></i> Выйти</a>
                </li>
              {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'users:register' %}">
                      <i class="fa fa-user-plus"></i> Зарегестрироваться</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'users:login' %}">
                      <i class="fa fa-arrow-right"></i> Войти</a>
                </li>
              {% endif %}
            </ul>
          </div>
    </nav>
    <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
          {% block page_header %}{% endblock page_header %}
        </div>
        <div>
          {% block content %}{% endblock content %}
        </div>
    </main>
  </body>
</html>

learning_logs/templates/learning_logs/delete_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

  <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

  <p>Удалить запись:</p>
  <form action="{% url 'learning_logs:delete_entry' entry.id %}" method="post"
        onsubmit="return confirm('Вы уверены, что хотите удалить эту запись?')">
    {% csrf_token %}
    <button name="submit">Удалить</button>
  </form>


{% endblock content %}

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
  <h3><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h3>
{% endblock page_header %}

{% block content %}

  <p>Редактировать запись:</p>
  <form action="{% url 'learning_logs:edit_entry' entry.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary mt-1">Сохранить изменения</button>
  </form>

{% endblock content %}

learning_logs/templates/learning_logs/edit_topic.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
  <h2>Редактировать тему</h2>
{% endblock page_header %}

{% block content %}

  <form action="{% url 'learning_logs:edit_topic' topic.id %}" method="post">
    {% csrf_token %}
    <div class="form-group">
      <label for="text">Название темы:</label>
      <input type="text" class="form-control" name="text" value="{{ topic.text }}" required>
    </div>
    <button type="submit" class="btn btn-primary">Сохранить изменения</button>
  </form>
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
  <div class="jumbotron">
    <h1 class="display-3">Отслеживайте свое обучение</h1>
    <p class="lead">Заведите свой собственный журнал обучения и ведите список тем,
        которые вы изучаете. Всякий раз, когда вы узнаете что-то новое по теме,
        делайте запись, в которой кратко изложите то, что вы узнали.</p>

    {% if not request.user.is_authenticated %}
    <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
       role="button">Зарегестрироваться &raquo;</a>
    {% endif %}
  </div>

{% endblock page_header %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
<h3><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h3>
{% endblock page_header %}

{% block content %}

  <p>Добавить новую запись:</p>
  <form action="{% url 'learning_logs:new_entry' topic.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary mt-1">Добавить запись</button>
  </form>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
  <h2>Добавить новую тему</h2>
{% endblock page_header %}

{% block content %}

  <form action="{% url 'learning_logs:new_topic' %}" method="post">
    {% csrf_token %}
    <div class="form-group">
      <label for="text">Название темы:</label>
      <input type="text" class="form-control" name="text" value="{{ topic.text }}" required>
    </div>
    <button type="submit" class="btn btn-primary">Добавить</button>
  </form>

{% endblock content %}

learning_logs/templates/learning_logs/old.html
<p>
    <a href="{% url 'learning_logs:index' %}">Learning log</a> -
    <a href="{% url 'learning_logs:topics' %}">Topics</a> -
    {% if user.is_authenticated %}
      Здравствуйте, {{ user.username }}.
      <a href="{% url 'users:logout' %}">Log out</a>
    {% else %}
      <a href="{% url 'users:register' %}">Register</a> -
      <a href="{% url 'users:login' %}">Log in</a>
    {% endif %}
</p>

{% block content %}{% endblock content %}





{% load tz %}
{% timezone "Europe/Moscow" %}
  <p><a href="{% url 'learning_logs:topics'%}">Тема: {{ topic }}</a></p>

  <p>Записи:</p>
  <p>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">Добавить новую запись</a>
  </p>
  <ul>
  {% for entry in entries %}
    <li>
      <p>{{ entry.date_added|date:'M d, Y H:i' }}</p>
      <p>{{ entry.text|linebreaks }}</p>
      <p>
        <a href="{% url 'learning_logs:edit_entry' entry.id %}">Редактировать запись</a>
      </p>
      <p>
        <a href="{% url 'learning_logs:delete_entry' entry.id %}">Удалить запись</a>
      </p>
    </li>
  {% empty %}
    <li>Записей по этой теме пока нет</li>
  {% endfor %}
  </ul>
{% endtimezone %}

{% endblock content %}




<small><a class="btn btn-sm btn-primary" href="{% url 'learning_logs:edit_entry' entry.id %}"
       role="button">редактировать</a></small>
        <small><a class="btn btn-sm btn-primary" href="{% url 'learning_logs:delete_entry' entry.id %}"
       role="button">удалить запись</a></small>

learning_logs/templates/learning_logs/topic.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
  <h3>{{ topic }}</h3>
{% endblock page_header %}

{% block content %}
{% load tz %}
{% timezone "Europe/Moscow" %}
  <p>
<a href="{% url 'learning_logs:new_entry' topic.id %}">Добавить новую запись</a>
  </p>

  {% for entry in entries %}
    <div class="card mb-3">
      <h4 class="card-header">
        {{ entry.date_added|date:'M d, Y H:i' }}
        <small><a href="{% url 'learning_logs:edit_entry' entry.id %}">редактировать запись</a></small>
        <small><a href="{% url 'learning_logs:delete_entry' entry.id %}">удалить запись</a></small>
      </h4>
      <div class="card-body">
        {{ entry.text|truncatechars:50|linebreaks }}
      </div>
    </div>
  {% empty %}
    <p>Записей по этой теме пока нет</p>
  {% endfor %}
{% endtimezone %}

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
  <h2>Темы</h2>
{% endblock page_header %}

{% block content %}

  <ul>
    {% for topic in topics %}
      <li><h3>
        <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
        <form action="{% url 'learning_logs:delete_topic' topic.id %}" method="post">
          {% csrf_token %}
          <button type="submit" class="btn-sm btn-primary mt-1">Удалить</button>
          <button type="button" class="btn-sm btn-primary mt-1 ml-2"
                  onclick="location.href='{% url 'learning_logs:edit_topic' topic.id %}'">Редактировать</button>
        </form>
      </h3></li>
    {% empty %}
      <li><h3>Еще не добавлено ни одной темы.</h3></li>
    {% endfor %}
  </ul>

  <h3><a href="{% url 'learning_logs:new_topic' %}">Добавить новую тему</a></h3>

{% endblock content %}